import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1775788347017 implements MigrationInterface {
    name = 'InitialSchema1775788347017'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS identity`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS reservation`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS notification`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS common`);
        await queryRunner.query(`CREATE TABLE "identity"."properties" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "type" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'trial', "trial_expires_at" TIMESTAMP, CONSTRAINT "UQ_185e77bff62276dd915c8be2198" UNIQUE ("external_id"), CONSTRAINT "PK_2d83bfa0b9fcd45dee1785af44d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "identity"."identity_staff_members" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "auth0_sub" character varying NOT NULL, "email" character varying NOT NULL, "name" character varying NOT NULL, "role" character varying NOT NULL, "property_id" uuid NOT NULL, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_59b9db0c9ad6a0cc49336543a0c" UNIQUE ("external_id"), CONSTRAINT "UQ_05ece324e4a4b63d0e3aca842ab" UNIQUE ("auth0_sub"), CONSTRAINT "PK_75d9cc86778abf691bef6b768d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reservation"."stays" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "phone" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'HOTEL', "whatsappNumber" character varying, CONSTRAINT "UQ_1be71b51bef405dde6597ddfe2d" UNIQUE ("external_id"), CONSTRAINT "UQ_8e3c68f56be2c63e27590de2c12" UNIQUE ("phone"), CONSTRAINT "PK_55e31a0cae0fd6ab1a9f3c6b593" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reservation"."rooms" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "stay_id" uuid NOT NULL, "capacity" integer NOT NULL, CONSTRAINT "UQ_58aeba8a4717c10df71538a6fa9" UNIQUE ("external_id"), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reservation"."staff_members" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "stay_id" uuid NOT NULL, "name" character varying NOT NULL, "email" character varying, "phone" character varying, "role" character varying NOT NULL DEFAULT 'ATTENDANT', "is_available" boolean NOT NULL DEFAULT true, "max_concurrent_sessions" integer NOT NULL DEFAULT '5', "current_sessions" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_3eec5b8be8c2145edbe4ce5da3f" UNIQUE ("external_id"), CONSTRAINT "UQ_84b814f9a703403b308835f8cc0" UNIQUE ("email"), CONSTRAINT "PK_cdad75efe024402db5d51140960" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reservation"."reservations" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "room_id" uuid NOT NULL, "session_id" uuid NOT NULL, "check_in" TIMESTAMP WITH TIME ZONE NOT NULL, "check_out" TIMESTAMP WITH TIME ZONE NOT NULL, "status" text NOT NULL DEFAULT 'HOLD', "expires_at" TIMESTAMP NOT NULL, CONSTRAINT "UQ_17d58bd4ab10808714dac904bf7" UNIQUE ("external_id"), CONSTRAINT "XCL_aa8b27ff3830782414d17ee00c" EXCLUDE USING gist (room_id WITH =, tstzrange(check_in, check_out, '[]') WITH &&) WHERE ("status" IN ('HOLD', 'CONFIRMED') AND "deleted_at" IS NULL), CONSTRAINT "PK_da95cef71b617ac35dc5bcda243" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reservation"."reservation_sessions" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "stay_id" uuid NOT NULL, "stay_name" character varying NOT NULL, "check_in" TIMESTAMP WITH TIME ZONE NOT NULL, "check_out" TIMESTAMP WITH TIME ZONE NOT NULL, "guests" integer NOT NULL, "staff_id" uuid NOT NULL, "status" text NOT NULL DEFAULT 'ACTIVE', "expires_at" TIMESTAMP NOT NULL, "customer" jsonb, "version" integer NOT NULL DEFAULT '1', CONSTRAINT "UQ_125c72cbeefccc93369b695d343" UNIQUE ("external_id"), CONSTRAINT "PK_b4170f2f0de1cd54ecbb5278688" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification"."notifications" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "recipient_id" uuid NOT NULL, "recipient_type" character varying NOT NULL, "channel" character varying NOT NULL, "destination" character varying NOT NULL, "stay_id" uuid NOT NULL, "event_type" character varying NOT NULL, "template_id" character varying NOT NULL, "payload" jsonb NOT NULL, "rendered_body" text NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "sent_at" TIMESTAMP, "failed_at" TIMESTAMP, "error" text, CONSTRAINT "UQ_def4fd3a4bd79c4331c2b84a2e1" UNIQUE ("external_id"), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification"."routing_rules" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "stayId" character varying NOT NULL, "eventType" character varying NOT NULL, "channel" character varying NOT NULL, "recipientType" character varying NOT NULL, "active" boolean NOT NULL, "quietHoursStart" character varying NOT NULL, "quietHoursEnd" character varying NOT NULL, CONSTRAINT "UQ_2f24f86761bc8be3529d1e94a05" UNIQUE ("external_id"), CONSTRAINT "PK_b744c5cc71053ea4d3fc8a860c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "common"."outbox_events" ("id" BIGSERIAL NOT NULL, "external_id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "queue" character varying NOT NULL, "payload" jsonb NOT NULL, "delay_seconds" integer NOT NULL DEFAULT '0', "published_at" TIMESTAMP, CONSTRAINT "UQ_fa435376c2ddb25aaf06e269bf6" UNIQUE ("external_id"), CONSTRAINT "PK_6689a16c00d09b8089f6237f1d2" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "common"."outbox_events"`);
        await queryRunner.query(`DROP TABLE "notification"."routing_rules"`);
        await queryRunner.query(`DROP TABLE "notification"."notifications"`);
        await queryRunner.query(`DROP TABLE "reservation"."reservation_sessions"`);
        await queryRunner.query(`DROP TABLE "reservation"."reservations"`);
        await queryRunner.query(`DROP TABLE "reservation"."staff_members"`);
        await queryRunner.query(`DROP TABLE "reservation"."rooms"`);
        await queryRunner.query(`DROP TABLE "reservation"."stays"`);
        await queryRunner.query(`DROP TABLE "identity"."identity_staff_members"`);
        await queryRunner.query(`DROP TABLE "identity"."properties"`);
        await queryRunner.query(`DROP SCHEMA IF EXISTS common`);
        await queryRunner.query(`DROP SCHEMA IF EXISTS notification`);
        await queryRunner.query(`DROP SCHEMA IF EXISTS reservation`);
        await queryRunner.query(`DROP SCHEMA IF EXISTS identity`);
    }

}
